# Generated by Django 5.0 on 2024-01-25 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_alter_emprestimos_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 25, 19, 28, 9, 677671)),
        ),
    ]
