# Generated by Django 5.0 on 2024-02-14 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0024_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 14, 13, 32, 5, 821697)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
